### PR TITLE
Update setup.py to reflect current Maintainers and Authors and updated project urls

### PR DESCRIPTION
**Pull request by IanHoang**
### Description
Currently, when users run `pip3 show opensearch-benchmark`, author and author emails are blank fields. This PR should change this for the next release.
```
$ pip3 show opensearch-benchmark
Name: opensearch-benchmark
Version: 1.5.0
Summary: Macrobenchmarking framework for OpenSearch
Home-page: https://github.com/opensearch-project/OpenSearch-Benchmark
Author:
Author-email:
License: Apache License, Version 2.0
Location: /home/ec2-user/.local/lib/python3.9/site-packages
Requires: boto3, certifi, google-auth, google-resumable-media, h5py, ijson, Jinja2, jsonschema, markupsafe, numpy, opensearch-py, psutil, py-cpuinfo, tabulate, thespian, wheel, yappi, zstandard
Required-by:
```

Tested it with OSB in developer mode
```
Name: opensearch-benchmark
Version: 1.6.0
Summary: Macrobenchmarking framework for OpenSearch
Home-page: https://github.com/opensearch-project/OpenSearch-Benchmark
Author: Ian Hoang, Govind Kamat, Mingyang Shi, Chinmay Gadgil, Rishabh Singh
Author-email: ianhoang16@gmail.com, govind_kamat@yahoo.com, mmyyshi@gmail.com, chinmay5j@gmail.com, rishabhksingh@gmail.com
```
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cgchinmay** [comment]
Would it be convenient to point to this [link](https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md) instead ?

**Review by beaioun — APPROVED** [review]

**Review by beaioun — APPROVED** [review]

**Comment by IanHoang** [comment]
> Would it be convenient to point to this [link](https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md) instead ?

We could try it. It looks like this if we change it to use the link. I did it the original way because opensearch-py seemed to be specifying the maintainers and authors explicitly. @gkamat @beaioun Feel free to let me know your preferences? I'm fine with using the maintainers file if that's simpler and requires less updating. 
```
Name: opensearch-benchmark
Version: 1.6.0
Summary: Macrobenchmarking framework for OpenSearch
Home-page: https://github.com/opensearch-project/OpenSearch-Benchmark
Author: https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md
Author-email: https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md
License: Apache License, Version 2.0
Location: /Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark
Editable project location: /Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark
Requires: boto3, certifi, google-auth, google-resumable-media, h5py, ijson, Jinja2, jsonschema, markupsafe, numpy, opensearch-py, psutil, py-cpuinfo, tabulate, thespian, wheel, yappi, zstandard
Required-by:
```

**Comment by cgchinmay** [comment]
> > Would it be convenient to point to this [link](https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md) instead ?
> 
> @cgchinmay We could try it. It looks like this if we change it to use the link. I did it the original way because opensearch-py seemed to be specifying the maintainers and authors explicitly. @gkamat @beaioun Feel free to let me know your preferences? I'm fine with using the maintainers file if that's simpler and requires less updating.
> 
> ```
> Name: opensearch-benchmark
> Version: 1.6.0
> Summary: Macrobenchmarking framework for OpenSearch
> Home-page: https://github.com/opensearch-project/OpenSearch-Benchmark
> Author: https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md
> Author-email: https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md
> License: Apache License, Version 2.0
> Location: /Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark
> Editable project location: /Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark
> Requires: boto3, certifi, google-auth, google-resumable-media, h5py, ijson, Jinja2, jsonschema, markupsafe, numpy, opensearch-py, psutil, py-cpuinfo, tabulate, thespian, wheel, yappi, zstandard
> Required-by:
> ```

No stromg pref, we can update it later if needed

**Review by cgchinmay — APPROVED** [review]

**Comment by beaioun** [comment]
> > Would it be convenient to point to this [link](https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md) instead ?
> 
> @cgchinmay We could try it. It looks like this if we change it to use the link. I did it the original way because opensearch-py seemed to be specifying the maintainers and authors explicitly. @gkamat @beaioun Feel free to let me know your preferences? I'm fine with using the maintainers file if that's simpler and requires less updating.
> 
> ```
> Name: opensearch-benchmark
> Version: 1.6.0
> Summary: Macrobenchmarking framework for OpenSearch
> Home-page: https://github.com/opensearch-project/OpenSearch-Benchmark
> Author: https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md
> Author-email: https://github.com/opensearch-project/opensearch-benchmark/blob/main/MAINTAINERS.md
> License: Apache License, Version 2.0
> Location: /Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark
> Editable project location: /Users/hoangia/Desktop/Development/opensearch-benchmark-ianhoang/opensearch-benchmark
> Requires: boto3, certifi, google-auth, google-resumable-media, h5py, ijson, Jinja2, jsonschema, markupsafe, numpy, opensearch-py, psutil, py-cpuinfo, tabulate, thespian, wheel, yappi, zstandard
> Required-by:
> ```

@IanHoang Yeah, I would prefer the current commit without the link. It would be better incorporated if we could find a way to redirect while hiding the link in the future.

**Pull request merged**
