### PR TITLE
Adding SigV4 support to opensearch-benchmarks for connecting to test clusters and results publishing

### PR DESCRIPTION
**Pull request by sachetalva**
### Description
This PR adds support in OpenSearch benchmark to connect to OpenSearch clusters using SigV4 for running tests or reporting test results.

New configuration options added with this change:
1. New parameters supported with `--client-options` argument in `execute-test`:
  - `amazon_aws_log_in`: Value can be one of `client-options` or `environment`
    - if `amazon_aws_log_in` is  set as `client-options`, then the below configuration is mandatory in client-options:
      - `aws_access_key_id`: The AWS access key ID to use
      - `aws_secret_access_key`: The AWS secret key to use
      - `service`: `es` for Amazon OpenSearch service
      - `region`: The region in which the cluster is available, example: `us-east-1`
    - if `amazon_aws_log_in` is  set as `environment`, then the below environment variables should be set:
      - `OSB_AWS_ACCESS_KEY_ID`: The AWS access key ID to use
      - `OSB_AWS_SECRET_ACCESS_KEY`: The AWS secret key to use
      - `OSB_SERVICE`: `es` for Amazon OpenSearch service
      - `OSB_REGION`: The region in which the cluster is available, example: `us-east-1`
2. New parameters in `reporting` section of benchmark.ini:
  - `datastore.amazon_aws_log_in`: Value can be one of `config` or `environment`
    - if `datastore.amazon_aws_log_in` is  set as `config`, then below configuration is mandatory in `reporting` section in benchmark.ini:
      -  `datastore.aws_access_key_id`: The AWS access key ID to use
      - `datastore.aws_secret_access_key`:  The AWS secret key to use
      - `datastore.service`: `es` for Amazon OpenSearch service
      - `datastore.region`: The region in which the cluster is available, example: `us-east-1`
    - if `datastore.amazon_aws_log_in` is  set as `environment`, then the below environment variables should be set:
      - `OSB_DATASTORE_AWS_ACCESS_KEY_ID`: The AWS access key ID to use
      - `OSB_DATASTORE_AWS_SECRET_ACCESS_KEY`: The AWS secret key to use
      - `OSB_DATASTORE_SERVICE`: `es` for Amazon OpenSearch service
      - `OSB_DATASTORE_REGION`: The region in which the cluster is available, example: `us-east-1`

### Issues Resolved
https://github.com/opensearch-project/opensearch-benchmark/issues/158

### Testing
- [x] New functionality includes testing
- [x] Executed `make test`
- [x] Executed benchmark tests using `percolator` and `http_logs` workloads using external OpenSearch cluster with SigV4 authentication for testing and another external OpenSearch cluster with SigV4 authentication for results reporting.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by IanHoang** [comment]
Thanks for taking a jab at this @sachetalva. to make it easier for others to understand this better and reproduce your tests, could you document how to use SigV4 in OSB?

**Comment by gkamat** [comment]
Thanks, @sachetalva.  Will take a look.  Does this rely on any associated changes in the `opensearchpy` client?

**Comment by sachetalva** [comment]
> Thanks for taking a jab at this @sachetalva. To make it easier for others to understand this better and reproduce your tests, could you document how to use SigV4 in OSB? We want to ensure that all changes that get merged into OSB are properly documented.

Updated the PR description with the details on how to enable SigV4 signing. I could not find any document which can be updated with these configuration details.

**Comment by sachetalva** [comment]
> Thanks, @sachetalva. Will take a look. Does this rely on any associated changes in the `opensearchpy` client?

Yes, we need an updated opensearch py client which supports SigV4 signing for async calls. Have updated the `opensearch-py[async]` dependency to `2.2.0`

**Comment by sachetalva** [comment]
Hi @IanHoang , @gkamat ,

I have rebased the code and updated the PR description as per the comments. Please do let me know if the changes look good.

**Comment by leejianwei** [comment]
What's the plan for this PR? BTW, what's the workaround to use OSB with Amazon OpenSearch services?

**Comment by IanHoang** [comment]
> Updated the PR description with the details on how to enable SigV4 signing. I could not find any document which can be updated with these configuration details.

Thanks @sachetalva for updating the PR description! Since this is a feature that's tailored to a specific cloud service, could you create a new document (such as "SIGV4_GUIDE.md") and add it to this PR? This document could briefly touch upon any prerequisites and provide a step-by-step walkthrough on how one could use SigV4 support within OSB. A document like this would smoothen the experience for community members who aren't familiar with AWS.

> What's the plan for this PR? BTW, what's the workaround to use OSB with Amazon OpenSearch services?
@leejianwei At this time, OSB can be used with Amazon OpenSearch services. Users just need to provide the endpoints to the `--target-hosts` parameter and provide FGAC credentials to `--client-options` parameter. This PR is strictly for enabling OpenSearch domains using SigV4 or AWS OpenSearch Serverless collections that require SigV4

**Comment by rishabh6788** [comment]
Just to confirm `opensearch-py` client is working correctly I followed the instructions in https://github.com/dblock/opensearch-python-client-demo and I was able to get response from the same endpoint used above.

**Comment by rishabh6788** [comment]
I was missing `amazon_aws_log_in:client_option` in the client-options. After adding that OSB process is able to move forward but it is stuck at `Running check-cluster-health` with below error:
```
2023-07-11 06:10:18,694 -not-actor-/PID:41263 opensearch WARNING GET https://search-test-sigv4-benchmark-6w454bptgpwdntbechlrsm54wi.us-east-1.es.amazonaws.com:443/_cluster/health/queries?wait_for_status=green&wait_for_no_relocating_shards=true [status:N/A request:10.498s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/opensearchpy/connection/http_async.py", line 200, in perform_request
    async with self.session.request(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 914, in start
    self._continue = None
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```
I can confirm that the cluster health is green:
```
sh-4.2$ curl   --request GET "https://search-test-sigv4-benchmark-6w454bptgpwdntbechlrsm54wi.us-east-1.es.amazonaws.com/_cluster/health"   --aws-sigv4 "aws:amz:us-east-1:es"   --user "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY"   -H "x-amz-security-token:$AWS_SESSION_TOKEN"
{"cluster_name":"592316141094:test-sigv4-benchmark","status":"green","timed_out":false,"number_of_nodes":6,"number_of_data_nodes":3,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":2,"active_shards":6,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
```

**Comment by bbarani** [comment]
@sachetalva Do you have any inputs here?

**Comment by rishabh6788** [comment]
Finally was able to wade through all the issues. 
The cluster health issue was only with AWS Managed with `Standby AZs` feature. The root cause was that when it is enabled the cluster expects all the indices to be created with n-1 replicas in n data node clusters. The OSB default config is 0 replica, when updated to 2 it worked fine. 
I do not see any other issue and it is working as expected. 
@IanHoang Please add your thoughts.

**Comment by rishabh6788** [comment]
Just want to callout that adding SIGv4 support to OSB doesn't mean it will work out of the box with AWS OpenSearch Serverless. The AOSS doesn't support cluster api and OSB would need major update to handle that.

**Comment by IanHoang** [comment]
Changes LGTM and we can merge this in

**Review by IanHoang — APPROVED** [review]

**Comment by cgchinmay** [comment]
@sachetalva Hi, I was trying to use sigv4 today and have following questions
1. Why is there no argument for session_token ? we use Role based access control and are required to pass session_token as well 
2. The service name in [documentation](https://opensearch.org/docs/latest/benchmark/tutorials/sigv4/) shows `aos` but I got an error. Only acceptable values are es and aoss . So which one to use ?
3. Our cluster is in VPC and I am using port forwarding , so the endpoint is 'https://localhost:9200' but I get following error
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /_cluster/health?wait_for_nodes=%3E%3D1 (Caused by SSLError(SSLCertVerificationError("hostname 'localhost' doesn't match '*.us-east-1.es.amazonaws.com'")))
```
Does the error mean that endpoint needs to be in fixed format ?

**Comment by sachetalva** [comment]
Hi @cgchinmay,
> Why is there no argument for session_token ? we use Role based access control and are required to pass session_token as well
Yes this support is not yet added. Role based credentials are short lived and hence might expire while the tests are running. For role based credentials, support could be added using the boto assume role provider or some other mechanism to fetch renewed credentials while the test is running.

> The service name in [documentation](https://opensearch.org/docs/latest/benchmark/tutorials/sigv4/) shows aos but I got an error. Only acceptable values are es and aoss . So which one to use ?
We can use "es" as mentioned this PR description. Documentation needs to be updated.

> Our cluster is in VPC and I am using port forwarding , so the endpoint is 'https://localhost:9200/' but I get following error
Could you try running benchmark from within the VPC using the VPC endpoint?

**Comment by cgchinmay** [comment]
> Hi @cgchinmay,
> 
> > Why is there no argument for session_token ? we use Role based access control and are required to pass session_token as well
> 

> Yes this support is not yet added. Role based credentials are short lived and hence might expire while the tests are running. For role based credentials, support could be added using the boto assume role provider or some other mechanism to fetch renewed credentials while the test is running.

Thanks for confirming

> > The service name in [documentation](https://opensearch.org/docs/latest/benchmark/tutorials/sigv4/) shows aos but I got an error. Only acceptable values are es and aoss . So which one to use ?
> 
> We can use "es" as mentioned this PR description. Documentation needs to be updated.

Okay 

> > Our cluster is in VPC and I am using port forwarding , so the endpoint is 'https://localhost:9200/' but I get following error
> 
> Could you try running benchmark from within the VPC using the VPC endpoint?

Yes, we could but the reason I was using port-forward so that I don't have to install opensearch-benchmark package on the bastion instance which is inside VPC. Will try it out though

**Comment by cgchinmay** [comment]
@sachetalva the error message that I see is SSLCertVerificationError and is expected when verify_certs is set to True
```
SSLError(SSLCertVerificationError("hostname '127.0.0.1' doesn't match '*.us-east-1.es.amazonaws.com'")))
```
So is there a way to disable this ? I tried passing it in client options as below but that didn't help
```
--client-options=timeout:120,amazon_aws_log_in:environment,use_ssl:false,verify_certs:false
```

**Pull request merged**
